/** Feature sub-pages (`/features/[slug]`). Compact data; the route builds the page. */
export interface Feature {
  slug: string;
  name: string;
  tagline: string;
  what: string[];     // bullet list of what it does
  why: string;        // one paragraph on why it matters
  group: string;      // "Email" | "Phone" | "Company" | "Platform"
}

export const FEATURES: Feature[] = [
  { slug: "catch-all-resolution", name: "Catch-all domain resolution", group: "Email", tagline: "Get a real signal on accept-all domains instead of a shrug.", what: ["Detect catch-all (accept-all) domains.", "Score their likely deliverability instead of marking everything valid.", "Flag the riskiest addresses to hold back."], why: "Catch-all domains accept mail for any address, so most verifiers can't tell you anything useful. We resolve as much signal as possible and fold it into a quality score, so you can send to the safe ones and hold the rest." },
  { slug: "disposable-detection", name: "Disposable email detection", group: "Email", tagline: "Keep throwaway addresses out of your list.", what: ["Match domains against a continuously updated disposable list.", "Flag temporary and throwaway providers.", "Block them at signup with the API."], why: "Disposable addresses self-destruct and never convert. Detecting them keeps your list clean and your engagement metrics honest, especially when paired with real-time form verification." },
  { slug: "spam-trap-detection", name: "Spam-trap detection", group: "Email", tagline: "Avoid the addresses that get you blocklisted.", what: ["Identify high-risk spam-trap patterns.", "Flag long-inactive and recycled addresses.", "Drop the riskiest contacts before you send."], why: "Hitting spam traps is one of the fastest ways to land on a blocklist. We flag the riskiest addresses so you can remove them before they damage your sender reputation." },
  { slug: "role-based-detection", name: "Role-based email detection", group: "Email", tagline: "Know which addresses go to a shared inbox.", what: ["Flag info@, sales@, support@ and similar.", "Let you exclude them from cold outreach.", "Keep them for transactional mail if you choose."], why: "Role accounts reach a function, not a person — they tend to engage less and complain more. Flagging them lets you decide how to treat them instead of mailing blind." },
  { slug: "syntax-mx-validation", name: "Syntax & MX validation", group: "Email", tagline: "Catch malformed addresses and dead domains first.", what: ["Validate address format and structure.", "Confirm the domain has MX records.", "Drop anything that can't possibly receive mail."], why: "Syntax and MX checks are the first line of defense — they catch obvious invalids and domains that can't receive mail at all, before any deeper (and slower) verification runs." },
  { slug: "typo-correction", name: "Typo & did-you-mean correction", group: "Email", tagline: "Recover real contacts hidden behind typos.", what: ["Spot common provider typos (gmial.com).", "Suggest the corrected address.", "Recover contacts you'd otherwise lose."], why: "A typo'd address bounces just like an invalid one — but the person behind it is real. Suggesting corrections recovers contacts you would otherwise throw away." },
  { slug: "deliverability-scoring", name: "Deliverability scoring", group: "Email", tagline: "Judge a whole list at a glance with one score.", what: ["Blend every signal into a 0-100 quality score.", "See list health before you pay.", "Compare lists over time."], why: "A single quality score blends syntax, domain, mailbox, catch-all and risk signals so you can judge an entire list at a glance — and decide whether it's safe to send before you commit." },
  { slug: "phone-line-type", name: "Phone line-type detection", group: "Phone", tagline: "Mobile, landline or VoIP — know before you dial.", what: ["Detect mobile, landline and VoIP numbers.", "Route SMS only to textable mobiles.", "Flag risky VoIP numbers."], why: "Line type changes how you reach someone. Texting a landline fails; VoIP numbers are often fraud or throwaways. Detecting line type lets you route outreach correctly and cut wasted sends." },
  { slug: "carrier-hlr-lookup", name: "Carrier & HLR lookup", group: "Phone", tagline: "Confirm a mobile number is live at the carrier.", what: ["Query carrier records for active status.", "See the current carrier, even after porting.", "Avoid dialing disconnected numbers."], why: "An HLR lookup checks a number against the carrier's own database, so you know whether it's active and which network it's on — far more reliable than a format check alone. It returns reachability and network status only, for numbers you're authorised to contact; it does not locate or track a person." },
  { slug: "fake-signup-prevention", name: "Fake-signup & bot prevention", group: "Platform", tagline: "Stop fake and bot signups at the form.", what: ["Block invalid, disposable and typo'd emails.", "Flag risky VoIP numbers and fake details.", "Verify in real time as the form submits."], why: "Guarding the form keeps fake and bot signups out of your CRM at the source — cheaper and cleaner than removing them later, and it keeps every downstream metric honest." },
  { slug: "name-to-domain-matching", name: "Company name-to-domain matching", group: "Company", tagline: "Resolve messy company names to real domains.", what: ["Match company names to primary domains.", "Handle abbreviations, suffixes and subsidiaries.", "Give every B2B record a reliable key."], why: "The domain is the most reliable key for a B2B account. Resolving messy form-entered company names to real domains is the foundation for deduplication, routing and enrichment." },
  { slug: "firmographic-enrichment", name: "Firmographic enrichment", group: "Company", tagline: "Add industry, size and location to your contacts.", what: ["Append industry, size and location.", "Enrich only verified, real contacts.", "Power lead scoring and routing."], why: "Firmographics turn a bare contact into a record you can segment and score. We enrich after verification, so you only add data to contacts that are actually real." },
  { slug: "bulk-list-cleaning", name: "Bulk list cleaning", group: "Platform", tagline: "Clean thousands of contacts in one upload.", what: ["Verify email and phone across the whole file.", "Dedupe even when formatting differs.", "Download a clean, annotated CSV."], why: "Upload a CSV and clean the entire list in minutes — email verified, phone validated, duplicates removed — then download a file you can send or import with confidence." },
  { slug: "webhooks-automation", name: "Webhooks & automation", group: "Platform", tagline: "Get notified when bulk jobs finish.", what: ["Fire a webhook when a job completes.", "Automate downstream imports and alerts.", "Build verify-then-sync pipelines."], why: "Webhooks let you wire verification into your own workflows — trigger an import, alert a channel, or kick off enrichment the moment a bulk job finishes, with no polling." },
  { slug: "sso-team-management", name: "SSO & team management", group: "Platform", tagline: "Bring your team onto one account.", what: ["Invite teammates to share your account.", "Manage roles and access.", "Single sign-on on higher tiers."], why: "Team management lets an account owner invite teammates to share the allowance and workspace, with roles and (on higher tiers) single sign-on for secure, centralized access." },
];

export function getFeature(slug: string) {
  return FEATURES.find((f) => f.slug === slug);
}
