/**
 * Unique per-feature context + FAQ for /features/[slug] — replaces the identical
 * "part of one clean pass" section and shared FAQ so no two feature pages match.
 */
export interface FeatureExtra {
  slug: string;
  context: string; // unique paragraph (replaces the templated closing section)
  faq: { q: string; a: string }[]; // 3 unique
}

export const FEATURE_EXTRA: FeatureExtra[] = [
  { slug: "catch-all-resolution", context: "Catch-all domains are where most verifiers give up and mark everything valid, inflating your apparent deliverability. We treat them as their own category and score the risk, so you can send to the safe ones and hold the rest rather than guessing.", faq: [{ q: "Why can't catch-alls be confirmed?", a: "An accept-all domain says yes to every address at the SMTP layer, so no verifier can confirm a specific mailbox from outside — the honest result is a catch-all flag, not a false valid." }, { q: "Should I send to catch-all addresses?", a: "Cautiously — start with engaged segments and weight them lower in your quality score, rather than treating them all as deliverable." }, { q: "Does the quality score account for them?", a: "Yes — catch-all risk feeds the 0-100 list score so you can set your own acceptance threshold." }] },
  { slug: "disposable-detection", context: "Disposable signups exist to grab a lead magnet or trial without giving a real address, so they inflate your numbers and never convert. Catching them — at the form or in a bulk clean — keeps your engagement metrics honest.", faq: [{ q: "How do you detect disposable domains?", a: "We match against a continuously updated list of known temporary-email providers, combined with other risk signals, since new disposable domains appear constantly." }, { q: "Can I block them at signup?", a: "Yes — the API rejects disposable domains in real time so they never become a record." }, { q: "Are all throwaways caught?", a: "We catch the large known set; full verification pairs this with deliverability checks to reduce what slips through." }] },
  { slug: "spam-trap-detection", context: "Spam traps are invisible to you but very visible to blocklist operators, and a single hit can filter all your mail. We flag the high-risk patterns and long-dormant addresses most likely to be traps so you can drop them before they cost you.", faq: [{ q: "Can you guarantee no spam traps?", a: "No tool can see every trap directly, but flagging the riskiest and long-inactive addresses dramatically lowers the odds of hitting one." }, { q: "What raises trap risk?", a: "Purchased lists, scraped data and addresses that have been inactive for a long time are the usual sources of recycled and pristine traps." }, { q: "What should I do with flagged addresses?", a: "Suppress them — the downside of removing a few real contacts is far smaller than a blocklist entry." }] },
  { slug: "role-based-detection", context: "Role addresses like info@ and sales@ reach a shared inbox, not a person, so they tend to engage less and complain more. Flagging them lets you decide their fate instead of mailing blind into a help desk.", faq: [{ q: "Should I remove role accounts?", a: "It depends on the send — many exclude them from cold outreach but keep them for transactional or account-level mail." }, { q: "Which prefixes count as role-based?", a: "Common ones include info, sales, support, admin, billing and contact, among others — we flag them so you can filter." }, { q: "Are they always bad?", a: "Not always, but they carry higher complaint risk, so the flag lets you treat them deliberately." }] },
  { slug: "syntax-mx-validation", context: "Syntax and MX checks are the cheap, fast first pass that removes the obviously broken before any deeper verification runs. They catch malformed addresses and domains that can't receive mail at all.", faq: [{ q: "What does an MX check tell you?", a: "Whether the domain has mail servers configured — if it doesn't, every address there will hard-bounce, so it's dropped early." }, { q: "Isn't valid syntax enough?", a: "No — a well-formed address can still be undeliverable; syntax is just the first filter before domain and mailbox checks." }, { q: "Does it catch typos?", a: "Obvious malformations, yes; provider typos like gmial.com are handled by the did-you-mean correction." }] },
  { slug: "typo-correction", context: "A typo'd address bounces exactly like an invalid one — but the person behind it is real and worth recovering. We surface a did-you-mean suggestion for common provider misspellings so you keep contacts you'd otherwise lose.", faq: [{ q: "Which typos do you catch?", a: "Common provider misspellings such as gmial.com, hotmial.com and yaho.com, where the intended domain is clear." }, { q: "Does it auto-fix addresses?", a: "It suggests the correction so you can confirm rather than silently changing a contact's address." }, { q: "Why does this matter?", a: "Recovering a mistyped address turns a guaranteed bounce back into a reachable, real contact." }] },
  { slug: "deliverability-scoring", context: "Per-address statuses are useful, but you also need to judge a whole list at a glance before you commit. The 0-100 quality score blends every signal so you can compare lists, set thresholds and decide if a file is safe to send.", faq: [{ q: "What goes into the score?", a: "Syntax, domain, MX and mailbox signals plus catch-all, disposable and role risk, blended into a single 0-100 number per list." }, { q: "How should I use it?", a: "Set an acceptance threshold for your risk tolerance, and review or hold addresses that fall below it." }, { q: "Can I compare lists over time?", a: "Yes — the score gives you a consistent benchmark to track list health across cleans." }] },
  { slug: "phone-line-type", context: "Line type decides how you reach someone: texting a landline fails, and VoIP numbers are over-represented in fraud and throwaways. Knowing the type lets you route SMS to mobiles and flag the risky numbers before a campaign.", faq: [{ q: "Why does line type matter?", a: "SMS only works on mobiles, calls suit landlines, and VoIP carries higher fraud risk — routing by type cuts wasted sends." }, { q: "Do you detect VoIP?", a: "Yes — VoIP is identified separately so you can add friction or extra verification for those numbers." }, { q: "Is this included with email verification?", a: "Yes — phone line type comes in the same upload as email checks." }] },
  { slug: "carrier-hlr-lookup", context: "For mobile numbers, an HLR lookup checks the carrier's own database for live status — far more reliable than a format check. It tells you whether a number is active and which network it's on, even after porting.", faq: [{ q: "What is an HLR lookup?", a: "A query against the carrier's Home Location Register that reveals whether a mobile number is active and its current network." }, { q: "Why is it better than format checks?", a: "Format only confirms a number looks right; HLR reflects its real status at the carrier, so you avoid dialing dead lines." }, { q: "Does it work after porting?", a: "Yes — it returns the current carrier even when a number has been ported." }] },
  { slug: "fake-signup-prevention", context: "The cleanest database is one that never lets bad data in. Verifying at the form — in real time — blocks invalid, disposable and bot signups before they become records, which is far cheaper than cleaning them up later.", faq: [{ q: "How does it block fakes at the form?", a: "Your form calls the API on submit; it returns a status in milliseconds so you can reject invalid, disposable and obviously fake entries inline." }, { q: "Will it slow down signups?", a: "No — checks return fast enough to validate as the user submits, with a graceful fallback." }, { q: "Does it cover phone too?", a: "Yes — it can flag risky VoIP numbers and malformed phones at the same time." }] },
  { slug: "name-to-domain-matching", context: "In B2B, the domain is the reliable key for an account, but forms capture messy company names. Resolving a name to its real primary domain is the foundation for deduplication, routing and enrichment.", faq: [{ q: "Why match to a domain?", a: "Company names are entered inconsistently; the domain is stable and unique, making it the best key for B2B records." }, { q: "How do you handle ambiguous names?", a: "We combine fuzzy matching with verification to avoid attaching data to the wrong company." }, { q: "What does it enable?", a: "Reliable dedupe, lead routing and firmographic enrichment that all hang off the resolved domain." }] },
  { slug: "firmographic-enrichment", context: "Firmographics turn a bare contact into an account you can segment and score — but only if the contact is real. We enrich after verification, so you add company, industry and size only to records worth keeping.", faq: [{ q: "Why enrich after verifying?", a: "Enriching invalid records wastes budget; verifying first means you only append data to contacts that actually exist." }, { q: "What fields do you add?", a: "Company, industry, size and location, matched from the contact's domain." }, { q: "What's it good for?", a: "Lead scoring, territory routing and personalised outreach based on real account attributes." }] },
  { slug: "bulk-list-cleaning", context: "Bulk cleaning runs the full verification engine across an entire file at once — email, phone, dedupe — and hands back a list you can send or import with confidence. It's the workhorse behind every pre-campaign clean.", faq: [{ q: "How large a list can I clean?", a: "Thousands of contacts per upload, processed in minutes with the same checks applied to every row." }, { q: "What do I get back?", a: "A verified CSV with per-row status, a quality score and duplicates removed." }, { q: "Does it dedupe?", a: "Yes — duplicates are caught even when formatting differs between rows." }] },
  { slug: "webhooks-automation", context: "Webhooks let you wire verification into your own systems — fire an event when a bulk job finishes and trigger the next step automatically, with no polling. It's how teams build verify-then-sync pipelines.", faq: [{ q: "When do webhooks fire?", a: "On completion of a bulk job, so you can trigger an import, an alert or an enrichment step the moment results are ready." }, { q: "Do I need to poll for status?", a: "No — the webhook pushes the completion event to your endpoint." }, { q: "What can I automate?", a: "Downstream imports, channel notifications and verify-then-enrich workflows." }] },
  { slug: "sso-team-management", context: "As your team grows, you want shared access without sharing logins. Team management lets an account owner invite teammates to share the allowance and workspace, with roles and single sign-on on higher tiers.", faq: [{ q: "Can I invite teammates?", a: "Yes — the account owner can invite teammates to share the workspace and allowance, up to the plan's seat limit." }, { q: "Is single sign-on available?", a: "SSO is offered on higher tiers for centralised, secure access." }, { q: "Can I control access?", a: "Yes — roles let you manage what each teammate can do." }] },
];

const map = new Map(FEATURE_EXTRA.map((e) => [e.slug, e]));
export function getFeatureExtra(slug: string): FeatureExtra | undefined {
  return map.get(slug);
}
